/datum/reagent/chlorine
/datum/reagent/carbondioxide
/datum/reagent/copper
/datum/reagent/silver
/datum/reagent/gold
/datum/reagent/cryptobiolin
/datum/reagent/spraytan
/datum/reagent/glycerol
/datum/reagent/cryostylane
/datum/reagent/medicine/muscle_stimulant
/datum/reagent/fungalspores
/datum/reagent/brimdust
/datum/reagent/medicine/coagulant/banana_peel
/datum/reagent/medicine/metafactor
/datum/reagent/medicine/c2
/datum/reagent/medicine/syndicate_nanites
/datum/reagent/metalgen
/datum/reagent/wittel
/datum/reagent/spider_extract
/datum/reagent/magillitis
/datum/reagent/exotic_stabilizer
/datum/reagent/gluttonytoxin
/datum/reagent/medicine/oxandrolone
/datum/reagent/medicine/sal_acid
/datum/reagent/medicine/pen_acid
/datum/reagent/phenol
/datum/reagent/medicine/higadrite
/datum/reagent/medicine/modafinil
/datum/reagent/medicine/cordiolis_hepatico
/datum/reagent/medicine/pyroxadone
/datum/reagent/medicine/psicodine
/datum/reagent/cyborg_mutation_nanomachines
/datum/reagent/medicine/c2/lenturi
/datum/reagent/bone_dust
/datum/reagent/medicine/rezadone
/datum/reagent/medicine/changelingadrenaline
/datum/reagent/medicine/changelinghaste
/datum/reagent/medicine/polypyr
/datum/reagent/peaceborg/confuse
/datum/reagent/medicine/activated_charcoal
/datum/reagent/hydrogen_peroxide
/datum/reagent/toxin/spewium
/datum/reagent/saltpetre
/datum/reagent/medicine/c2/syriniver
/datum/reagent/peaceborg/tire
/datum/reagent/medicine/c2/penthrite
/datum/reagent/medicine/coagulant/seraka_extract
/datum/reagent/c2/helbital
/datum/reagent/medicine/silibinin
/datum/reagent/plasma_oxide
/datum/reagent/gondola_mutation_toxin
/datum/reagent/medicine/synaphydramine
/datum/reagent/medicine/c2/helbital
