/datum/hud/blob_overmind/initialize_screens()
	. = ..()
	add_screen_object(/atom/movable/screen/blob/blob_power, HUDKEY_BLOB_POWER_DISPLAY, HUDGROUP_INFO_DISPLAY)
	add_screen_object(/atom/movable/screen/healths/blob, HUDKEY_MOB_HEALTH, HUDGROUP_INFO_DISPLAY)

	add_screen_object(/atom/movable/screen/blob/blob_help, HUDKEY_BLOB_HELP, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/jump_to_node, HUDKEY_BLOB_JUMP_TO_NODE, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/jump_to_core, HUDKEY_BLOB_JUMP_TO_CORE, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/blobbernaut, HUDKEY_BLOB_BLOBBERNAUT, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/resource_blob, HUDKEY_BLOB_RESOURCES, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/node_blob, HUDKEY_BLOB_NODE, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/factory_blob, HUDKEY_BLOB_FACTORY, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/readapt_strain, HUDKEY_BLOB_READAPT, HUDGROUP_STATIC_INVENTORY)
	add_screen_object(/atom/movable/screen/blob/relocate_core, HUDKEY_BLOB_RELOCATE, HUDGROUP_STATIC_INVENTORY)
