#define DIRECTIVE_SEVERITY_LOW "low"
#define DIRECTIVE_SEVERITY_MED "medium"
#define DIRECTIVE_SEVERITY_HIGH "high"

#define DIRECTIVE_CONTINUE 0
#define DIRECTIVE_SUCCESS 1
#define DIRECTIVE_FAILURE 2
