#define FLOCK_TYPE_OVERMIND "overmind"
#define FLOCK_TYPE_TRACE "trace"
#define FLOCK_TYPE_DRONE "drone"
#define FLOCK_TYPE_BIT "bit"

#define FLOCK_NOTICE_RESERVED "reserved"
#define FLOCK_NOTICE_PRIORITY "priority"
#define FLOCK_NOTICE_ENEMY "enemy"
#define FLOCK_NOTICE_IGNORE "ignore"
#define FLOCK_NOTICE_FLOCKTRACE_CONTROL "flocktrace_control"
#define FLOCK_NOTICE_FLOCKMIND_CONTROL "flockmind_control"

#define FLOCK_UI_DRONES "drones"
#define FLOCK_UI_TRACES "traces"
#define FLOCK_UI_ENEMIES "enemies"
