//Gamemode weights
#define GAMEMODE_WEIGHT_NEVER 0

#define GAMEMODE_WEIGHT_LEGENDARY 10
#define GAMEMODE_WEIGHT_EPIC 30
#define GAMEMODE_WEIGHT_RARE 50
#define GAMEMODE_WEIGHT_UNCOMMON 70
#define GAMEMODE_WEIGHT_COMMON 100
