#define THIRST_STAGE_BLOODLUST 1
#define THIRST_STAGE_SATED 2
#define THIRST_STAGE_HUNGRY 3
#define THIRST_STAGE_STARVING 4
#define THIRST_STAGE_WASTING 5

// Point thresholds to change stages. 1 point = 1 second
#define THIRST_THRESHOLD_BLOODLUST 0
#define THIRST_THRESHOLD_SATED 300
#define THIRST_THRESHOLD_HUNGERY (THIRST_THRESHOLD_SATED + 300)
#define THIRST_THRESHOLD_STARVING (THIRST_THRESHOLD_HUNGERY + 300)
#define THIRST_THRESHOLD_WASTING (THIRST_THRESHOLD_STARVING + 300)
#define THIRST_THRESHOLD_DEAD (THIRST_THRESHOLD_WASTING + 300)
