//Defines Factions
#define FACTION_NCR "NCR"
#define FACTION_LEGION "Legion"
#define FACTION_BROTHERHOOD "BOS"
#define FACTION_OASIS "Town"
#define FACTION_ENCLAVE "Enclave"
#define FACTION_WASTELAND "Wastelander"
#define FACTION_RAIDERS "Raiders"
#define FACTION_TRIBE "Tribe"
#define FACTION_VAULT "Vault"
#define FACTION_FOLLOWERS "Followers"
