#include "_combat.dm"

#include "combat.dm"
#include "combat_blocking.dm"
#include "combat_cuffs.dm"
#include "combat_door_click.dm"
#include "combat_emp_flashlight.dm"
#include "combat_flash.dm"
#include "combat_nested_inventory.dm"
#include "combat_pistol_whip.dm"
#include "combat_stamina.dm"
